# -*- coding: utf-8 -*-
"""HackathonRF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17GXTKJxoLZt_8HyobSOE3XnsCyW1WuAj
"""

from google.colab import files
import pandas as pd
import io

print("Lütfen masaüstünden 'merged_output_ready.csv' dosyasını seç:")
uploaded = files.upload()

filename = next(iter(uploaded))
df = pd.read_csv(io.BytesIO(uploaded[filename]))

print(f"\n✅ {filename} başarıyla yüklendi!")
print("--- Sütun İsimleri ---")
print(df.columns.tolist())
display(df.head())

df["timestamp"] = pd.to_datetime(df["timestamp"])

df = df.sort_values("timestamp").reset_index(drop=True)

print("📌 Veri zaman aralığı:")
print("Başlangıç :", df["timestamp"].min())
print("Bitiş     :", df["timestamp"].max())

print("\n📌 Toplam satır sayısı:", len(df))

display(df.head(3))
display(df.tail(3))

TARGET_ROUTE = "YENIKAPI - HAVALIMANI_YENIKAPI"

print("🎯 Pilot hat:", TARGET_ROUTE)

route_df = df[[
    "timestamp",
    TARGET_ROUTE,
    "hour",
    "day_of_week",
    "month"
]].copy()

route_df.rename(columns={TARGET_ROUTE: "density"}, inplace=True)

print("\n📊 Satır sayısı:", len(route_df))
print("📉 Yoğunluk min:", route_df["density"].min())
print("📈 Yoğunluk max:", route_df["density"].max())

display(route_df.head())
display(route_df.tail())

route_df["density_t_plus_1h"] = route_df["density"].shift(-1)

print("🧪 NaN sayısı:", route_df["density_t_plus_1h"].isna().sum())

check_df = route_df[[
    "timestamp",
    "density",
    "density_t_plus_1h"
]].head(10)

display(check_df)

feature_cols = [
    "hour",
    "day_of_week",
    "month",
    "density"
]

target_col = "density_t_plus_1h"

model_df = route_df[feature_cols + [target_col]].dropna()

print("📊 Model veri seti boyutu:", model_df.shape)
display(model_df.head())

X = model_df[feature_cols]
y = model_df[target_col]

split_index = int(len(model_df) * 0.8)

X_train = X.iloc[:split_index]
X_test  = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test  = y.iloc[split_index:]

print("🟢 Train boyutu:", X_train.shape)
print("🔵 Test boyutu :", X_test.shape)

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

rf = RandomForestRegressor(
    n_estimators=200,
    max_depth=10,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"📉 MAE  : {mae:.4f}")
print(f"📊 RMSE : {rmse:.4f}")

def best_departure_time(current_row, model, max_wait=3):
    """
    current_row : şu anki satır (df.loc[i])
    max_wait    : kaç saat sonrasına kadar bakılsın
    """

    results = []

    for h in range(max_wait + 1):
        hour = (current_row["hour"] + h) % 24

        X_future = [[
            hour,
            current_row["day_of_week"],
            current_row["month"],
            current_row["density"]
        ]]

        pred_density = model.predict(X_future)[0]

        results.append({
            "wait_hours": h,
            "predicted_density": round(pred_density, 4)
        })

    return pd.DataFrame(results)

def best_departure_time(current_row, model, max_wait=3):

    results = []
    base_density = current_row["density"]

    for h in range(max_wait + 1):
        future_hour = (current_row["hour"] + h) % 24

        X_future = [[
            future_hour,
            current_row["day_of_week"],
            current_row["month"],
            base_density
        ]]

        pred_density = model.predict(X_future)[0]

        results.append({
            "wait_hours": h,
            "predicted_density": round(pred_density, 4)
        })

    return pd.DataFrame(results)

sample_row = route_df.iloc[1000]

decision_df = best_departure_time(sample_row, rf, max_wait=3)
decision_df

def decision_text(decision_df):

    best_row = decision_df.loc[
        decision_df["predicted_density"].idxmin()
    ]

    wait = int(best_row["wait_hours"])
    best_density = best_row["predicted_density"]
    now_density = decision_df.loc[0, "predicted_density"]

    improvement = (now_density - best_density) / now_density * 100

    if wait == 0:
        return "🚦 Şu anda çıkmak en uygun zaman."

    return (
        f"⏳ {wait} saat sonra yola çıkarsanız "
        f"yoğunluk yaklaşık %{improvement:.1f} azalıyor. "
        f"Daha konforlu bir yolculuk için beklemeniz önerilir."
    )

print(decision_text(decision_df))

def minute_level_decision(decision_df, minute_steps=[15, 30, 45]):

    rows = []

    now_density = decision_df.loc[0, "predicted_density"]
    next_density = decision_df.loc[1, "predicted_density"]

    for m in minute_steps:
        ratio = m / 60
        interpolated_density = (
            now_density * (1 - ratio) + next_density * ratio
        )

        rows.append({
            "wait_minutes": m,
            "predicted_density": round(interpolated_density, 4)
        })

    return pd.DataFrame(rows)

minute_df = minute_level_decision(decision_df)
minute_df

import matplotlib.pyplot as plt

def plot_density_forecast(decision_df):

    plt.figure(figsize=(8, 4))
    plt.plot(
        decision_df["wait_hours"],
        decision_df["predicted_density"],
        marker="o"
    )

    plt.xlabel("Bekleme Süresi (saat)")
    plt.ylabel("Tahmini Yoğunluk")
    plt.title("Yoğunluk Tahmini – Zaman")
    plt.grid(True)
    plt.show()

plot_density_forecast(decision_df)

routes = [
    "YENIKAPI - HAVALIMANI_YENIKAPI",
    "YENIKAPI - HAVALIMANI_ZEYTINBURNU",
    "YENIKAPI - HAVALIMANI_YENIBOSNA"
]

def compare_routes(df, routes, model, row_index=1000):

    results = []

    for route in routes:
        temp_df = df[[
            "timestamp", route, "hour", "day_of_week", "month"
        ]].copy()

        temp_df.rename(columns={route: "density"}, inplace=True)

        current_row = temp_df.iloc[row_index]

        X = [[
            current_row["hour"],
            current_row["day_of_week"],
            current_row["month"],
            current_row["density"]
        ]]

        pred_density = model.predict(X)[0]

        results.append({
            "route": route,
            "predicted_density": round(pred_density, 4)
        })

    return pd.DataFrame(results).sort_values("predicted_density")

compare_df = compare_routes(df, routes, rf)
compare_df

def route_decision_text(compare_df):

    best = compare_df.iloc[0]
    worst = compare_df.iloc[-1]

    improvement = (
        (worst["predicted_density"] - best["predicted_density"])
        / worst["predicted_density"] * 100
    )

    return (
        f"🚦 En konforlu rota: {best['route']}\n"
        f"📉 Yoğunluk farkı: %{improvement:.1f} daha az\n"
        f"❌ Kaçınılması önerilen rota: {worst['route']}"
    )

print(route_decision_text(compare_df))

def density_to_class(d):
    if d < 0.33:
        return "Rahat"
    elif d < 0.66:
        return "Orta"
    else:
        return "Yogun"

y_pred_reg = y_pred
y_true_reg = y_test.values

y_pred_cls = [density_to_class(v) for v in y_pred_reg]
y_true_cls = [density_to_class(v) for v in y_true_reg]

from sklearn.metrics import classification_report

print(classification_report(
    y_true_cls,
    y_pred_cls,
    digits=3
))

from sklearn.metrics import confusion_matrix
import pandas as pd

cm = confusion_matrix(
    y_true_cls,
    y_pred_cls,
    labels=["Rahat", "Orta", "Yogun"]
)

cm_df = pd.DataFrame(
    cm,
    index=["Gerçek_Rahat", "Gerçek_Orta", "Gerçek_Yogun"],
    columns=["Tahmin_Rahat", "Tahmin_Orta", "Tahmin_Yogun"]
)

cm_df

cm_norm = cm.astype("float") / cm.sum(axis=1, keepdims=True)

plt.figure(figsize=(6, 5))
plt.imshow(cm_norm, cmap="Blues")
plt.title("Normalized Confusion Matrix (%)")
plt.xlabel("Tahmin")
plt.ylabel("Gerçek")

plt.xticks(np.arange(len(class_names)), class_names)
plt.yticks(np.arange(len(class_names)), class_names)

for i in range(len(class_names)):
    for j in range(len(class_names)):
        plt.text(
            j, i, f"{cm_norm[i, j]*100:.1f}%",
            ha="center", va="center",
            color="black"
        )

plt.colorbar()
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

feature_importance = pd.DataFrame({
    "feature": feature_cols,
    "importance": rf.feature_importances_
}).sort_values("importance", ascending=False)

feature_importance

plt.figure(figsize=(7,4))
plt.barh(
    feature_importance["feature"],
    feature_importance["importance"]
)
plt.gca().invert_yaxis()
plt.xlabel("Önem")
plt.title("Feature Importance (Random Forest)")
plt.tight_layout()
plt.show()

!pip install shap

import shap

explainer = shap.TreeExplainer(rf)
shap_values = explainer.shap_values(X_train)

shap.summary_plot(shap_values, X_train)

i = 10  # herhangi bir index
shap.force_plot(
    explainer.expected_value,
    shap_values[i],
    X_train.iloc[i],
    matplotlib=True
)

